### ISSUE TITLE
Running EnhancedVolcano in a loop renders blank output

### ISSUE THREAD

**Issue by limrock1** [kevinblighe/EnhancedVolcano#3] opened 2018-11-12 20:46 UTC
Hi Kevin,

I just started using you tool, lovely piece of work. I'm stumbing on one issue though and not sure if it's my setup or what:

I run a piece of code in Rstudio which basically generates a DESeq output object for multiple comps in a dataset. For each result object, I return various plots and tables, one of which is an EnhancedVolcano pdf. Everytime I get a an empty pdf rendered. 
If I plot the pdf for any one result object individually, it plots just fine. All other plots and tables output fine in the loop, just EnhancedVolcano is empty.

The loop looks like this:

```
for (t in unique(All_groups)){
  seen <- append(seen, t)
  for (t2 in All_groups){
    if(t2 == t) next
    if(t2 %in% seen) next 
    testGroup <- t
    ctrlGroup <- t2 #setdiff(All_groups,t)

```   
    ...... run DiffExpr for test v ctrl .......

    # 1. Dispersion Estimate
    message("Plotting Dispersion")
    pdf(file=paste(outDir,testGroup,"_v_",ctrlGroup,".dispersionEstimate.pdf", sep=""),width=10, height=8)
    plotDispEsts(DE_dds)
    dev.off()
    # 2. MAplot of 2-way comparison
    message("Plotting MA")
    pdf(file=paste(outDir,testGroup,"_v_",ctrlGroup,".MA_plot.pdf", sep=""),width=10, height=8)
    DESeq2::plotMA(result_out,ylim=c(-5,5), alpha=0.05, main=paste(testGroup, " v ", ctrlGroup))
    dev.off()
    # 2b. 2-way comparison using EnhancedVolcanoPlot 
    message("Plotting Volcano")
    pdf(file=paste(outDir,testGroup,"_v_",ctrlGroup,".Volcano_plot.pdf", sep=""),
        width=10,height=8)
    EnhancedVolcano(result_out, x="log2FoldChange", y="padj",
                    lab=rownames(result_out),
                    FCcutoff = 1.5, pCutoff = 1e-4,
                    #xlim=c(-5,5), ylim=c(0,-log10(10e-40)),
                    colAlpha = 0.8,
                    legendPosition = "right",
                    legend=c("NS","Log2 FC","Adjusted p-value",
                             "Adj p-value & Log2 FC"),
                    title = paste(testGroup, " v ", ctrlGroup),
                    gridlines.major = FALSE,
                    gridlines.minor = FALSE)
    dev.off()
    .... continue with loop .....

Any ideas by any chance?
Sean

**Comment by kevinblighe** [comment] 2018-11-13 00:12
Hey Sean, thanks for using _EnhancedVolcano_ and thanks for the comments! I was able to reproduce the issue and also fix it by wrapping the `EnhancedVolcano(...)` function with `plot()`. So:

```
pdf(file=paste(outDir,testGroup,"_v_",ctrlGroup,".Volcano_plot.pdf", sep=""),
    width=10,height=8)
plot(EnhancedVolcano(result_out, x="log2FoldChange", y="padj",
                lab=rownames(result_out),
                FCcutoff = 1.5, pCutoff = 1e-4,
                #xlim=c(-5,5), ylim=c(0,-log10(10e-40)),
                colAlpha = 0.8,
                legendPosition = "right",
                legend=c("NS","Log2 FC","Adjusted p-value",
                         "Adj p-value & Log2 FC"),
                title = paste(testGroup, " v ", ctrlGroup),
                gridlines.major = FALSE,
                gridlines.minor = FALSE))
dev.off()

...
```
Let me know if that solves it?

Kind regards,
Kevin

**Comment by kevinblighe** [comment] 2018-11-13 10:18
Yes, the function normally returns a ggplot2 object, which is usually enough to invoke the plot window. Let me explore it further as to what was happening

**Comment by kevinblighe** [comment] 2018-11-13 17:14
It seems to be a well documented issue with ggplot objects. When in a loop, they have to be explicitly generated via `plot()` or `print()`. I will close this issue. Others with the same problem will probably find this issue via their search engine.

Kind regards,
Kevin

**Closed by kevinblighe** 2018-11-13 17:14 UTC

**Comment by limrock1** [comment] 2018-11-13 17:22
Appreciate it. Once again, thanks for a great tool Kevin - my new go-to plot.

**Comment by sandra444** [comment] 2019-08-01 12:42
Thanks for posting this question and answer. It was very helpful!
